swagger: '2.0'
x-stoplight:
  id: uehx6n863bpvv
info:
  title: 2.0Yaml
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  '/users/{userId}':
    parameters:
      - type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          schema:
            $ref: '#/definitions/User'
          examples:
            Get User Alice Smith:
              id: 142
              firstName: Alice
              lastName: Smith
              email: alice.smith@gmail.com
              dateOfBirth: '1997-10-31'
              emailVerified: true
              signUpDate: '2019-08-24'
        '404':
          description: User Not Found
          schema:
            type: 'null'
          examples: {}
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: ber90z8xj2939
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          schema:
            $ref: '#/definitions/User'
          examples:
            Update User Rebecca Baker:
              id: 13
              firstName: Rebecca
              lastName: Baker
              email: rebecca@gmail.com
              dateOfBirth: '1985-10-02'
              emailVerified: false
              createDate: '2019-08-24'
        '404':
          description: User Not Found
          schema:
            type: 'null'
        '409':
          description: Email Already Taken
          schema:
            type: 'null'
      description: Update the information of an existing user.
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
                description: 'If a new email is given, the user''s email verified property will be set to false.'
              dateOfBirth:
                type: string
          description: Patch user properties to update.
          x-examples:
            Update First Name:
              firstName: Rebecca
            Update Email:
              email: rebecca@gmail.com
            Update Last Name & Date of Birth:
              lastName: Baker
              dateOfBirth: '1985-10-02'
      x-stoplight:
        id: fc24uyctur07r
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Missing Required Information
          schema:
            type: 'null'
        '409':
          description: Email Already Taken
          schema:
            type: 'null'
      description: Create a new user.
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              dateOfBirth:
                type: string
                format: date
            required:
              - firstName
              - lastName
              - email
              - dateOfBirth
          description: Post the necessary fields for the API to create a new user.
          x-examples:
            Create User Bob Fellow:
              firstName: Bob
              lastName: Fellow
              email: bob.fellow@gmail.com
              dateOfBirth: '1996-08-24'
      x-stoplight:
        id: hvpq4d9zhk55y
  /new/test/users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
            application/x-bittorrent:
              schema:
                type: object
                properties: {}
      operationId: get-new-test-users
      x-stoplight:
        id: ygm0466x9l6hh
    options:
      summary: Your OPTIONS endpoint
      tags: []
      responses:
        '205':
          description: Reset Content
          schema:
            allOf:
              - x-stoplight:
                  id: bsa4cy468arlt
                properties:
                  resref1:
                    $ref: 'stoplight://resources/overrides/YS7QQySZYz0'
                  resRef2:
                    $ref: 'stoplight://resources/overrides/BL3xE9PfKLs'
                  resRef3:
                    $ref: 'https://stoplight.io/api/v1/projects/persistentteams/dlcreation1418/nodes/models/AllOFTestModel.json?mid=40918'
            type: object
      operationId: options-new-test-users
      x-stoplight:
        id: rjcdwtf7crrlq
      parameters:
        - in: body
          name: body
          schema:
            allOf:
              - properties:
                  reqREf1:
                    $ref: 'stoplight://resources/overrides/YS7QQySZYz0'
                  reqref2:
                    $ref: 'stoplight://resources/overrides/BL3xE9PfKLs'
                  reqref3:
                    $ref: 'stoplight://resources/overrides/5YcFm4h43KE'
            type: object
definitions:
  User:
    title: User
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the given user.
        x-stoplight:
          id: 7pjuh6hll57pn
      firstName:
        type: string
        x-stoplight:
          id: n36nh7kj2ym6l
      lastName:
        type: string
        x-stoplight:
          id: 7vcbft4ksn4tu
      email:
        type: string
        format: email
        x-stoplight:
          id: 91zba9fphidm1
      dateOfBirth:
        type: string
        format: date
        example: '1997-10-31'
        x-stoplight:
          id: qotpxdvt2x9n8
      emailVerified:
        type: boolean
        description: Set to true if the user's email has been verified.
        x-stoplight:
          id: ssobqe3dur47q
      createDate:
        type: string
        format: date
        description: The date that the user was created.
        x-stoplight:
          id: 4ufuxowyd4j5v
    required:
      - id
      - firstName
      - lastName
      - email
      - emailVerified
    x-stoplight:
      id: 9foarfua4b08a
